### ISSUE TITLE
🐞 Multiple issues encountered in Quickstart example code

### ISSUE THREAD

**Issue by lumisong** [Quantmetry/qolmat#68]
Hello! While trying to run the Quickstart example code, I stumbled across several issues:

1. **API Parameter Name Changes** 🔄:
   - For `imputer_rpca`, the parameter `max_iter` seems to have been changed to `max_iterations`.
   - Similarly, for `imputer_knn`, the parameter `k` is now `n_neighbors`.

2. **Variable Name Inconsistencies** 🤔:
   - The `readme` refers to a variable as `dict_config_opti`, but in the code, it's actually named `search_params`.

3. **Missing Imports** 📥:
   - The example code doesn't include `from qolmat.benchmark import missing_patterns`.

4. **Parameter Name Changes in comparator.Comparator** 🚧:
   - The `n_calls_opt` parameter should now be `max_evals`.

5. **Execution Error** ❌:
   - After addressing the above issues, I ran `results = comparison.compare(df_with_nan)` and faced an error during the `ImputerRPCA` segment. The error message was: `unsupported operand type(s) for -: 'float' and 'dict'`.

To ensure a better onboarding experience for new users and potential contributors, I'd kindly suggest that you revisit and execute the Quickstart once more. Making sure the provided guide runs smoothly can greatly help in fostering user trust and ease of contribution.

I hope these points can be tackled to ensure a smoother experience for future users with this library. Thanks in advance for looking into these! 🙏

**Comment by JulienRoussel77** [comment]
Hello Xiaohu Zheng, thank you for your constructive feedback ! Indeed the quickstart has not been correctly updated during the latest release, and we apologize for the inconvenience. As a temporary solution I suggest to base your tests on this [notebook](https://github.com/Quantmetry/qolmat/blob/main/examples/benchmark.md) which is more reliable.

We are currently working on integrating the code extracts from the doc in our CICD in order to avoid the situation you experienced. The package is functional but still in in development, please keep us updated on the issues you are facing and on features you think are lacking or counter-intuitive!

Cheers

**Comment by JulienRoussel77** [comment]
The issues you stumbled across have been patched in the version 0.1.0 we just published . The documentation has been fully reworked, and multiple features have been added! Thanks again for you feedback
